### ISSUE TITLE
Xor publish clean files

### ISSUE THREAD

**Issue by peterthorpe81** [stavroskasidis/BlazorWasmAntivirusProtection#13]
The CleanOldDlls function doesn't appear to work correctly with the Xor process. I think this is due to the the IsDllHeaderBz check being incorrect when the file is Xor'ed.

If you run a publish the files are Xored if you run another publish straight after the files are reverted unless you manually clean the directory.

**Comment by stavroskasidis** [comment]
I can reproduce it. A fix will be coming.

**Comment by stavroskasidis** [comment]
Fixed in 1.6
