### ISSUE TITLE
StaticWebAssetBasePath set on the client project is not respected

### ISSUE THREAD

**Issue by gldraphael** [stavroskasidis/BlazorWasmAntivirusProtection#16]
I have a hosted blazor project where `<StaticWebAssetBasePath>` is set on the client project in order to serve the blazor wasm app from a subdirectory. The blazor wasm app's `index.html` has a `<base href="/app/" />` set, which inturn causes the browser to load everything from `/app`.

However `BlazorWasmAntivirusProtection.lib.module.js` is only available at `https://localhost:15563/_content/BlazorWasmAntivirusProtection/BlazorWasmAntivirusProtection.lib.module.js` and not at `https://localhost:15563/app/_content/BlazorWasmAntivirusProtection/BlazorWasmAntivirusProtection.lib.module.js`.

I've opened a PR so that it's easier to see a repro https://github.com/stavroskasidis/BlazorWasmAntivirusProtection/pull/15.

If I figure what needs to change, I'll post an update.

**Comment by stavroskasidis** [comment]
Thank you for reporting this. I will push a fix asap.

**Comment by stavroskasidis** [comment]
Actually upon further investigation, it seems that this is the default behavior of referenced RazorClassLibraries.
This seems like a misconfiguration you are dealing with.

You can check the `test/webassetspath-change` branch where I got it working.

The differences compared to your PR were the following lines:
```
app.UseBlazorFrameworkFiles("/app");
app.UseStaticFiles();
app.UseStaticFiles("/app");
```

**Comment by gldraphael** [comment]
Thank you. I was indeed missing a `app.UseStaticFiles("/app")`.

Closing.

**Comment by legistek** [comment]
Thank you, I had the same problem and the `app.UseStaticFiles("/app");` line also solved it. I'm writing here because, oddly enough, I already had a line ` app.UseStaticFiles(new StaticFileOptions {...});` for the `v3` `RequestPath`  but I still needed the standalone line `app.UseStaticFiles("/app");`  in addition to that. Just some odd ASP.NET behavior I suppose but point being, you might need both lines.
