### ISSUE TITLE
Is your solution compatible with prerendering?

### ISSUE THREAD

**Issue by Andrzej-W** [stavroskasidis/BlazorWasmAntivirusProtection#21]
Hello Stavros

I temporarily abandoned my Blazor project about a year ago because there where too many problems - one of them was high risk of firewall/antivirus blocking. Your solution seems perfect. My project is a public website that must be properly indexed by Google and other robots. To achieve this I have to use prerendering.

Is your solution compatible with prerendering? You wrote that assemblies are obfuscated during publishing. Do you leave original files so they can be used on the server in the prerendering phase?

**Comment by stavroskasidis** [comment]
Yes it should be compatible since the server project has its own copy of the assemblies. The client assemblies are in a separate folder when published, exactly because they get trimmed and compressed and stuff.

**Comment by Andrzej-W** [comment]
Thank you for your time and effort. Hopefully I will soon find some free time to come back to my Blazor project and test your solution.
