### ISSUE TITLE
Zscaller corporate proxy (not working)

### ISSUE THREAD

**Issue by fdonnet** [stavroskasidis/BlazorWasmAntivirusProtection#31]
I tried to open an issue here too : https://github.com/dotnet/aspnetcore/issues/44782

Did someone has any xp with this messy proxy ? I cannot access anything in term of policies or config but it stops my wasm blazor very well.

**Comment by fdonnet** [comment]
your tool fights Zscaller if a specify .dat extension (.bin seems blocked too by my corporate config) you can add it to the list of success. Thx a lot for your job on this very very useful.

**Comment by fdonnet** [comment]
maybe it will be good to set another default value (.bin) seems to be considered as executable by dummy proxies. Maybe to have a excellent "first try xp".  A simple rename to .dat didn't do the trick for me. So the obfuscation part was important too and your custom caching is much loved. 👍

**Comment by stavroskasidis** [comment]
Thank you for your feedback, much appreciated. I am happy this solution worked for you
