### ISSUE TITLE
Problem when using a RuntimeIdentifier (win-x64)

### ISSUE THREAD

**Issue by Tealons** [stavroskasidis/BlazorWasmAntivirusProtection#38]
We would like to implement BlazorWasmAntivirusProtection because of problems at one of our customers, but adding the nuget packages the build steps are not executed. 

After some trial and error we found out that the problem is caused by the runtime identifier we use to build our project. Removing `<RuntimeIdentifier>win-x64</RuntimeIdentifier>` from our server csproj makes the build step to be executed. 

We have the feeling that the extra folder in the bin folder for the runtimeidentifier is the cause, but we don't know where in the package this is a problem.

So building the project without the runtimeidentifier gives the following path: 
`Server\bin\Release\net7.0\publish\wwwroot\_framework`

With runtime identifier it becomes: 
`Server\bin\Release\net7.0\win-x64\publish\wwwroot\_framework`

Is this something that can be fixed in the next version?

**Comment by Tealons** [comment]
I have the feeling the problem is in this part of the task registration:

```
<UsingTask TaskName="BlazorWasmAntivirusProtection.Tasks.ObfuscateDlls"
				 AssemblyFile="$(MSBuildThisProjectFileDirectory)..\..\..\tasks\BlazorWasmAntivirusProtection.Tasks.dll" />
<UsingTask TaskName="BlazorWasmAntivirusProtection.Tasks.RenameDlls"
		AssemblyFile="$(MSBuildThisProjectFileDirectory)..\..\..\tasks\BlazorWasmAntivirusProtection.Tasks.dll" />
<UsingTask TaskName="BlazorWasmAntivirusProtection.Tasks.CleanOldDlls"
	AssemblyFile="$(MSBuildThisProjectFileDirectory)..\..\..\tasks\BlazorWasmAntivirusProtection.Tasks.dll" />
```

But I'm having trouble putting my finger on it..

**Comment by stavroskasidis** [comment]
I cannot reproduce it. I added `<RuntimeIdentifier>win-x64</RuntimeIdentifier>` to my project and it worked fine:
![image](https://user-images.githubusercontent.com/12549761/202839704-fad9ecbb-8968-4f06-9d10-f9c4f57e41db.png)
![image](https://user-images.githubusercontent.com/12549761/202839718-22cc7446-5cc7-4078-b261-b88934ad57f6.png)

What error are you getting? Did you add the package to both Server and Client projects?

**Comment by Tealons** [comment]
Yes, but now I see I had the wrong version on one of the projects. Als our build in Azure DevOps is quite complicated. I just found out how to get it running there by simplifying stuff. So sorry for this issue. The problem was not the runtimeidentifier.

**Comment by Tealons** [comment]
Got it to work on our development environment today! Thanks for a great package @stavroskasidis !!
